#!/usr/bin/env python3
"""
Builds the launch screen's breathing mark from docs/branding/logo.png.

The design is docs/branding/splash-pulse-reference.gif: the mark dims to a little under half its
brightness and comes back, on a two-second loop. Run from anywhere:
`python3 docs/branding/build-splash.py`

## Why frames, and not the GIF

Android's launch screen cannot play a GIF. From Android 12 it plays an animated drawable as the
icon, and an `animation-list` of bitmaps is one, so the pulse is rebuilt here as frames — from the
clean transparent source rather than from the GIF, whose 256-colour palette bands the gradients in
the dragon's scales.

## Why so few frames, and why they repeat

Every frame of an animation-list is decoded up front, and a launch screen is the moment an app has
the least memory to spare — on a television most of all. So there are seven brightness levels at
640px, about 1.6 MB each, and the loop walks down them and back up. A frame named twice is the same
resource, which the platform decodes once.

Below Android 12 the launch screen draws a static icon, so drawable/ic_mihon_splash.xml stays the
undimmed mark and this writes the animation to drawable-v31.

## The size

A launch icon with no background of its own is drawn on a 288dp canvas and masked to a 192dp
circle, so the mark is scaled to two thirds of its canvas — the same rule as the launcher icon, for
the same reason: any larger and the circle takes the dragon's head.
"""

import math
from pathlib import Path

import numpy as np
from PIL import Image

BRANDING = Path(__file__).parent
SOURCE = BRANDING / "logo.png"
RES = BRANDING.parent.parent / "animato-app" / "src" / "main" / "res"

FRAME_SIZE = 640
ARTWORK_FRACTION = 192 / 288

# Measured off the reference: its mean brightness falls from 44.5 to 20.6, which is 46%.
DIMMEST = 0.46
LEVELS = 7

# The reference loops in 1920 ms. Seven levels down and back up is twelve frames.
LOOP_MS = 1920


def mark_on_canvas():
    source = Image.open(SOURCE).convert("RGBA")
    alpha = np.asarray(source)[:, :, 3]
    rows = np.where((alpha > 20).any(axis=1))[0]
    cols = np.where((alpha > 20).any(axis=0))[0]
    mark = source.crop((cols.min(), rows.min(), cols.max() + 1, rows.max() + 1))

    longest = round(FRAME_SIZE * ARTWORK_FRACTION)
    scale = longest / max(mark.size)
    mark = mark.resize((round(mark.width * scale), round(mark.height * scale)), Image.LANCZOS)
    canvas = Image.new("RGBA", (FRAME_SIZE, FRAME_SIZE), (0, 0, 0, 0))
    canvas.alpha_composite(mark, ((FRAME_SIZE - mark.width) // 2, (FRAME_SIZE - mark.height) // 2))
    return canvas


def dimmed(image, factor):
    pixels = np.asarray(image).astype(float)
    pixels[:, :, :3] *= factor
    return Image.fromarray(pixels.round().astype(np.uint8), "RGBA")


def main():
    mark = mark_on_canvas()
    nodpi = RES / "drawable-nodpi"
    nodpi.mkdir(parents=True, exist_ok=True)

    # The static mark below Android 12, and frame 0 of the loop above it.
    mark.save(nodpi / "animato_splash_mark.png", optimize=True)

    names = []
    for level in range(LEVELS):
        # Eased, so it lingers at both ends the way the reference does, rather than bouncing.
        t = level / (LEVELS - 1)
        factor = 1 - (1 - DIMMEST) * (1 - math.cos(math.pi * t)) / 2
        name = "animato_splash_mark" if level == 0 else f"animato_splash_pulse_{level}"
        if level:
            dimmed(mark, factor).save(nodpi / f"{name}.png", optimize=True)
        names.append(name)

    sequence = names + names[-2:0:-1]
    duration = LOOP_MS // len(sequence)
    items = "\n".join(
        f'    <item android:drawable="@drawable/{name}" android:duration="{duration}" />' for name in sequence
    )
    v31 = RES / "drawable-v31"
    v31.mkdir(parents=True, exist_ok=True)
    (v31 / "ic_mihon_splash.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!--\n"
        "  The launch mark breathing: dims to just under half and back, on a two-second loop.\n"
        "  Generated by docs/branding/build-splash.py, which says why it is frames and why so few.\n"
        "  Android 12 and later only; below that the launch screen draws drawable/ic_mihon_splash.xml.\n"
        "-->\n"
        '<animation-list xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:oneshot="false">\n'
        f"{items}\n"
        "</animation-list>\n",
        encoding="utf8",
    )
    print(f"wrote {len(names)} levels, {len(sequence)} frames at {duration} ms")


if __name__ == "__main__":
    main()
