package animato.di

import io.kotest.matchers.shouldBe
import org.junit.jupiter.api.Test

/**
 * The graph is generated by Metro's compiler plugin. Without the plugin, everything still compiles —
 * `createGraphFactory` is an ordinary function whose body throws "Implemented by the compiler" — and
 * the app dies on launch. That happened once, when the plugin line was lost from the build file.
 */
class AnimatoGraphGeneratedTest {

    @Test
    fun `Metro generated the graph`() {
        runCatching { Class.forName("animato.di.AnimatoGraph\$Impl") }.isSuccess shouldBe true
    }
}
