// Generated by .github/generate-injekt-accessors.py — do not edit by hand. Run it again after
// adding an Injekt request; CI fails while this file is out of date.
package animato.di

import android.app.Application
import android.content.Context
import animato.anime.content.LiveChannels
import animato.anime.iptv.M3uPlaylistStore
import animato.anime.jellyfin.JellyfinServerStore
import animato.anime.net.ProxyPreferences
import animato.anime.player.RememberedQuality
import animato.anime.player.SubtitleDelayMemory
import animato.anime.player.cast.CastController
import animato.anime.services.download.EpisodeVideoResolver
import animato.anime.stremio.StremioAddonDirectory
import animato.anime.stremio.StremioAddonStore
import animato.anime.stremio.StremioSubtitleFinder
import animato.anime.torznab.TorznabIndexerStore
import animato.anime.track.AnimeTrackerManager
import animato.app.discover.DiscoverPreferences
import animato.app.discover.MetadataCatalog
import animato.app.downloads.DownloadCleanupPreferences
import animato.app.entry.EntryOverrides
import animato.app.library.UnifiedLibraryPreferences
import animato.app.sync.SyncPreferences
import animato.domain.content.ContentPreferences
import animato.domain.content.interactor.GetUnifiedLibrary
import aniyomi.core.common.torrent.TorrentPreferences
import aniyomi.core.common.torrent.TorrentServerApi
import aniyomi.core.common.torrent.TorrentServerUtils
import aniyomi.domain.download.service.AnimeDownloadPreferences
import aniyomi.domain.library.service.AnimeLibraryPreferences
import aniyomi.domain.source.interactor.SetAnimeMigrateSorting
import aniyomi.domain.source.service.AnimeSourcePreferences
import aniyomi.domain.track.service.AnimeTrackPreferences
import eu.kanade.domain.base.BasePreferences
import eu.kanade.domain.chapter.interactor.SetReadStatus
import eu.kanade.domain.entries.anime.interactor.SetAnimeViewerFlags
import eu.kanade.domain.entries.anime.interactor.UpdateAnime
import eu.kanade.domain.extension.anime.interactor.GetAnimeExtensionLanguages
import eu.kanade.domain.extension.anime.interactor.GetAnimeExtensionSources
import eu.kanade.domain.extension.anime.interactor.GetAnimeExtensionsByType
import eu.kanade.domain.extension.anime.interactor.TrustAnimeExtension
import eu.kanade.domain.extension.interactor.GetExtensionsByType
import eu.kanade.domain.items.episode.interactor.SetSeenStatus
import eu.kanade.domain.manga.interactor.UpdateManga
import eu.kanade.domain.source.anime.interactor.GetAnimeIncognitoState
import eu.kanade.domain.source.anime.interactor.GetAnimeSourcesWithFavoriteCount
import eu.kanade.domain.source.anime.interactor.GetEnabledAnimeSources
import eu.kanade.domain.source.anime.interactor.GetLanguagesWithAnimeSources
import eu.kanade.domain.source.anime.interactor.ToggleAnimeIncognito
import eu.kanade.domain.source.anime.interactor.ToggleAnimeSource
import eu.kanade.domain.source.anime.interactor.ToggleAnimeSourcePin
import eu.kanade.domain.source.interactor.GetIncognitoState
import eu.kanade.domain.source.interactor.ToggleLanguage
import eu.kanade.domain.source.service.SourcePreferences
import eu.kanade.domain.track.anime.interactor.AddAnimeTracks
import eu.kanade.domain.track.anime.interactor.RefreshAnimeTracks
import eu.kanade.domain.track.anime.interactor.TrackEpisode
import eu.kanade.domain.track.anime.store.DelayedAnimeTrackingStore
import eu.kanade.domain.track.interactor.AddTracks
import eu.kanade.domain.track.interactor.RefreshTracks
import eu.kanade.domain.track.service.TrackPreferences
import eu.kanade.domain.ui.UiPreferences
import eu.kanade.tachiyomi.core.security.SecurityPreferences
import eu.kanade.tachiyomi.data.backup.create.creators.CategoriesBackupCreator
import eu.kanade.tachiyomi.data.backup.create.creators.ExtensionStoresBackupCreator
import eu.kanade.tachiyomi.data.backup.create.creators.MangaBackupCreator
import eu.kanade.tachiyomi.data.backup.create.creators.PreferenceBackupCreator
import eu.kanade.tachiyomi.data.backup.create.creators.SourcesBackupCreator
import eu.kanade.tachiyomi.data.backup.restore.restorers.CategoriesRestorer
import eu.kanade.tachiyomi.data.backup.restore.restorers.ExtensionStoreRestorer
import eu.kanade.tachiyomi.data.backup.restore.restorers.MangaRestorer
import eu.kanade.tachiyomi.data.backup.restore.restorers.PreferenceRestorer
import eu.kanade.tachiyomi.data.cache.AnimeBackgroundCache
import eu.kanade.tachiyomi.data.cache.AnimeCoverCache
import eu.kanade.tachiyomi.data.cache.ChapterCache
import eu.kanade.tachiyomi.data.download.DownloadCache
import eu.kanade.tachiyomi.data.download.DownloadManager
import eu.kanade.tachiyomi.data.download.DownloadProvider
import eu.kanade.tachiyomi.data.download.anime.AnimeDownloadCache
import eu.kanade.tachiyomi.data.download.anime.AnimeDownloadManager
import eu.kanade.tachiyomi.data.download.anime.AnimeDownloadProvider
import eu.kanade.tachiyomi.data.saver.ImageSaver
import eu.kanade.tachiyomi.data.track.TrackerManager
import eu.kanade.tachiyomi.extension.ExtensionManager
import eu.kanade.tachiyomi.extension.anime.AnimeExtensionManager
import eu.kanade.tachiyomi.network.JavaScriptEngine
import eu.kanade.tachiyomi.network.NetworkHelper
import eu.kanade.tachiyomi.network.NetworkPreferences
import eu.kanade.tachiyomi.torrentutils.TorrentInfoProvider
import eu.kanade.tachiyomi.ui.player.ExternalIntents
import eu.kanade.tachiyomi.ui.player.settings.AdvancedPlayerPreferences
import eu.kanade.tachiyomi.ui.player.settings.AudioPreferences
import eu.kanade.tachiyomi.ui.player.settings.DecoderPreferences
import eu.kanade.tachiyomi.ui.player.settings.GesturePreferences
import eu.kanade.tachiyomi.ui.player.settings.PlayerPreferences
import eu.kanade.tachiyomi.ui.player.settings.SubtitlePreferences
import eu.kanade.tachiyomi.ui.player.utils.TrackSelect
import kotlinx.serialization.json.Json
import kotlinx.serialization.protobuf.ProtoBuf
import mihon.domain.extension.anime.interactor.AddAnimeExtensionStore
import mihon.domain.extension.anime.interactor.GetAnimeExtensionStoreCountAsFlow
import mihon.domain.extension.anime.interactor.GetAnimeExtensionStores
import mihon.domain.extension.anime.interactor.RemoveAnimeExtensionStore
import mihon.domain.extension.anime.interactor.UpdateAnimeExtensionStores
import mihon.domain.extension.anime.repository.AnimeExtensionStoreRepository
import mihon.domain.extension.interactor.GetExtensionStoreCountAsFlow
import mihon.domain.items.episode.interactor.FilterEpisodesForDownload
import mihon.domain.source.interactor.UpdateAnimeFromRemote
import mihon.domain.source.interactor.UpdateMangaFromRemote
import mihon.domain.upcoming.anime.interactor.GetUpcomingAnime
import nl.adaptivity.xmlutil.serialization.XML
import tachiyomi.core.common.preference.PreferenceStore
import tachiyomi.data.handlers.anime.AnimeDatabaseHandler
import tachiyomi.domain.backup.service.BackupPreferences
import tachiyomi.domain.category.anime.interactor.CreateAnimeCategoryWithName
import tachiyomi.domain.category.anime.interactor.DeleteAnimeCategory
import tachiyomi.domain.category.anime.interactor.GetAnimeCategories
import tachiyomi.domain.category.anime.interactor.GetVisibleAnimeCategories
import tachiyomi.domain.category.anime.interactor.HideAnimeCategory
import tachiyomi.domain.category.anime.interactor.RenameAnimeCategory
import tachiyomi.domain.category.anime.interactor.ReorderAnimeCategory
import tachiyomi.domain.category.anime.interactor.SetAnimeCategories
import tachiyomi.domain.category.anime.interactor.SetAnimeDisplayMode
import tachiyomi.domain.category.anime.interactor.SetSortModeForAnimeCategory
import tachiyomi.domain.category.interactor.GetCategories
import tachiyomi.domain.chapter.interactor.GetChapter
import tachiyomi.domain.chapter.interactor.GetChaptersByMangaId
import tachiyomi.domain.chapter.interactor.UpdateChapter
import tachiyomi.domain.custombuttons.interactor.CreateCustomButton
import tachiyomi.domain.custombuttons.interactor.DeleteCustomButton
import tachiyomi.domain.custombuttons.interactor.GetCustomButtons
import tachiyomi.domain.custombuttons.interactor.ReorderCustomButton
import tachiyomi.domain.custombuttons.interactor.ToggleFavoriteCustomButton
import tachiyomi.domain.custombuttons.interactor.UpdateCustomButton
import tachiyomi.domain.download.service.DownloadPreferences
import tachiyomi.domain.entries.anime.interactor.AnimeFetchInterval
import tachiyomi.domain.entries.anime.interactor.GetAnime
import tachiyomi.domain.entries.anime.interactor.GetAnimeByUrlAndSourceId
import tachiyomi.domain.entries.anime.interactor.GetAnimeFavorites
import tachiyomi.domain.entries.anime.interactor.GetAnimeWithEpisodesAndSeasons
import tachiyomi.domain.entries.anime.interactor.GetDuplicateLibraryAnime
import tachiyomi.domain.entries.anime.interactor.GetLibraryAnime
import tachiyomi.domain.entries.anime.interactor.NetworkToLocalAnime
import tachiyomi.domain.entries.anime.interactor.SetAnimeEpisodeFlags
import tachiyomi.domain.entries.anime.interactor.SetAnimeSeasonFlags
import tachiyomi.domain.entries.anime.repository.AnimeRepository
import tachiyomi.domain.history.anime.interactor.GetAnimeHistory
import tachiyomi.domain.history.anime.interactor.GetNextEpisodes
import tachiyomi.domain.history.anime.interactor.RemoveAnimeHistory
import tachiyomi.domain.history.anime.interactor.UpsertAnimeHistory
import tachiyomi.domain.history.interactor.GetHistory
import tachiyomi.domain.items.episode.interactor.GetEpisode
import tachiyomi.domain.items.episode.interactor.GetEpisodeByUrlAndAnimeId
import tachiyomi.domain.items.episode.interactor.GetEpisodesByAnimeId
import tachiyomi.domain.items.episode.interactor.SetAnimeDefaultEpisodeFlags
import tachiyomi.domain.items.episode.interactor.UpdateEpisode
import tachiyomi.domain.items.season.interactor.GetAnimeSeasonsByParentId
import tachiyomi.domain.items.season.interactor.SetAnimeDefaultSeasonFlags
import tachiyomi.domain.library.service.LibraryPreferences
import tachiyomi.domain.manga.interactor.GetFavorites
import tachiyomi.domain.manga.interactor.GetLibraryManga
import tachiyomi.domain.manga.interactor.GetManga
import tachiyomi.domain.manga.interactor.GetMangaWithChapters
import tachiyomi.domain.manga.interactor.NetworkToLocalManga
import tachiyomi.domain.manga.repository.MangaRepository
import tachiyomi.domain.source.anime.interactor.GetRemoteAnime
import tachiyomi.domain.source.anime.service.AnimeSourceManager
import tachiyomi.domain.source.service.SourceManager
import tachiyomi.domain.storage.service.StorageManager
import tachiyomi.domain.storage.service.StoragePreferences
import tachiyomi.domain.track.anime.interactor.DeleteAnimeTrack
import tachiyomi.domain.track.anime.interactor.GetAnimeTracks
import tachiyomi.domain.track.anime.interactor.GetTracksPerAnime
import tachiyomi.domain.track.anime.interactor.InsertAnimeTrack
import tachiyomi.domain.track.anime.repository.AnimeTrackRepository
import tachiyomi.domain.track.repository.TrackRepository
import tachiyomi.domain.updates.anime.interactor.GetAnimeUpdates
import tachiyomi.domain.updates.interactor.GetUpdates
import tachiyomi.source.local.image.anime.LocalAnimeBackgroundManager
import tachiyomi.source.local.image.anime.LocalAnimeCoverManager
import tachiyomi.source.local.image.anime.LocalEpisodeThumbnailManager
import tachiyomi.source.local.io.anime.LocalAnimeSourceFileSystem
import java.lang.reflect.Type

/**
 * One accessor per type this fork asks Injekt for, so that Metro has to be able to build each of
 * them — a request nothing provides is a compile error in [AnimatoGraph]. See the generator.
 */
interface InjektAccessors {
    val addAnimeExtensionStore: AddAnimeExtensionStore
    val addAnimeTracks: AddAnimeTracks
    val addTracks: AddTracks
    val advancedPlayerPreferences: AdvancedPlayerPreferences
    val animeBackgroundCache: AnimeBackgroundCache
    val animeCoverCache: AnimeCoverCache
    val animeDatabaseHandler: AnimeDatabaseHandler
    val animeDownloadCache: AnimeDownloadCache
    val animeDownloadManager: AnimeDownloadManager
    val animeDownloadPreferences: AnimeDownloadPreferences
    val animeDownloadProvider: AnimeDownloadProvider
    val animeExtensionManager: AnimeExtensionManager
    val animeExtensionStoreRepository: AnimeExtensionStoreRepository
    val animeFetchInterval: AnimeFetchInterval
    val animeLibraryPreferences: AnimeLibraryPreferences
    val animeRepository: AnimeRepository
    val animeSourceManager: AnimeSourceManager
    val animeSourcePreferences: AnimeSourcePreferences
    val animeTrackPreferences: AnimeTrackPreferences
    val animeTrackRepository: AnimeTrackRepository
    val animeTrackerManager: AnimeTrackerManager
    val application: Application
    val audioPreferences: AudioPreferences
    val backupPreferences: BackupPreferences
    val basePreferences: BasePreferences
    val castController: CastController
    val categoriesBackupCreator: CategoriesBackupCreator
    val categoriesRestorer: CategoriesRestorer
    val chapterCache: ChapterCache
    val contentPreferences: ContentPreferences
    val context: Context
    val createAnimeCategoryWithName: CreateAnimeCategoryWithName
    val createCustomButton: CreateCustomButton
    val decoderPreferences: DecoderPreferences
    val delayedAnimeTrackingStore: DelayedAnimeTrackingStore
    val deleteAnimeCategory: DeleteAnimeCategory
    val deleteAnimeTrack: DeleteAnimeTrack
    val deleteCustomButton: DeleteCustomButton
    val discoverPreferences: DiscoverPreferences
    val downloadCache: DownloadCache
    val downloadCleanupPreferences: DownloadCleanupPreferences
    val downloadManager: DownloadManager
    val downloadPreferences: DownloadPreferences
    val downloadProvider: DownloadProvider
    val entryOverrides: EntryOverrides
    val episodeVideoResolver: EpisodeVideoResolver
    val extensionManager: ExtensionManager
    val extensionStoreRestorer: ExtensionStoreRestorer
    val extensionStoresBackupCreator: ExtensionStoresBackupCreator
    val externalIntents: ExternalIntents
    val filterEpisodesForDownload: FilterEpisodesForDownload
    val gesturePreferences: GesturePreferences
    val getAnime: GetAnime
    val getAnimeByUrlAndSourceId: GetAnimeByUrlAndSourceId
    val getAnimeCategories: GetAnimeCategories
    val getAnimeExtensionLanguages: GetAnimeExtensionLanguages
    val getAnimeExtensionSources: GetAnimeExtensionSources
    val getAnimeExtensionStoreCountAsFlow: GetAnimeExtensionStoreCountAsFlow
    val getAnimeExtensionStores: GetAnimeExtensionStores
    val getAnimeExtensionsByType: GetAnimeExtensionsByType
    val getAnimeFavorites: GetAnimeFavorites
    val getAnimeHistory: GetAnimeHistory
    val getAnimeIncognitoState: GetAnimeIncognitoState
    val getAnimeSeasonsByParentId: GetAnimeSeasonsByParentId
    val getAnimeSourcesWithFavoriteCount: GetAnimeSourcesWithFavoriteCount
    val getAnimeTracks: GetAnimeTracks
    val getAnimeUpdates: GetAnimeUpdates
    val getAnimeWithEpisodesAndSeasons: GetAnimeWithEpisodesAndSeasons
    val getCategories: GetCategories
    val getChapter: GetChapter
    val getChaptersByMangaId: GetChaptersByMangaId
    val getCustomButtons: GetCustomButtons
    val getDuplicateLibraryAnime: GetDuplicateLibraryAnime
    val getEnabledAnimeSources: GetEnabledAnimeSources
    val getEpisode: GetEpisode
    val getEpisodeByUrlAndAnimeId: GetEpisodeByUrlAndAnimeId
    val getEpisodesByAnimeId: GetEpisodesByAnimeId
    val getExtensionStoreCountAsFlow: GetExtensionStoreCountAsFlow
    val getExtensionsByType: GetExtensionsByType
    val getFavorites: GetFavorites
    val getHistory: GetHistory
    val getIncognitoState: GetIncognitoState
    val getLanguagesWithAnimeSources: GetLanguagesWithAnimeSources
    val getLibraryAnime: GetLibraryAnime
    val getLibraryManga: GetLibraryManga
    val getManga: GetManga
    val getMangaWithChapters: GetMangaWithChapters
    val getNextEpisodes: GetNextEpisodes
    val getRemoteAnime: GetRemoteAnime
    val getTracksPerAnime: GetTracksPerAnime
    val getUnifiedLibrary: GetUnifiedLibrary
    val getUpcomingAnime: GetUpcomingAnime
    val getUpdates: GetUpdates
    val getVisibleAnimeCategories: GetVisibleAnimeCategories
    val hideAnimeCategory: HideAnimeCategory
    val imageSaver: ImageSaver
    val insertAnimeTrack: InsertAnimeTrack
    val javaScriptEngine: JavaScriptEngine
    val jellyfinServerStore: JellyfinServerStore
    val json: Json
    val libraryPreferences: LibraryPreferences
    val liveChannels: LiveChannels
    val localAnimeBackgroundManager: LocalAnimeBackgroundManager
    val localAnimeCoverManager: LocalAnimeCoverManager
    val localAnimeSourceFileSystem: LocalAnimeSourceFileSystem
    val localEpisodeThumbnailManager: LocalEpisodeThumbnailManager
    val m3uPlaylistStore: M3uPlaylistStore
    val mangaBackupCreator: MangaBackupCreator
    val mangaRepository: MangaRepository
    val mangaRestorer: MangaRestorer
    val metadataCatalog: MetadataCatalog
    val networkHelper: NetworkHelper
    val networkPreferences: NetworkPreferences
    val networkToLocalAnime: NetworkToLocalAnime
    val networkToLocalManga: NetworkToLocalManga
    val playerPreferences: PlayerPreferences
    val preferenceBackupCreator: PreferenceBackupCreator
    val preferenceRestorer: PreferenceRestorer
    val preferenceStore: PreferenceStore
    val protoBuf: ProtoBuf
    val proxyPreferences: ProxyPreferences
    val refreshAnimeTracks: RefreshAnimeTracks
    val refreshTracks: RefreshTracks
    val rememberedQuality: RememberedQuality
    val removeAnimeExtensionStore: RemoveAnimeExtensionStore
    val removeAnimeHistory: RemoveAnimeHistory
    val renameAnimeCategory: RenameAnimeCategory
    val reorderAnimeCategory: ReorderAnimeCategory
    val reorderCustomButton: ReorderCustomButton
    val securityPreferences: SecurityPreferences
    val setAnimeCategories: SetAnimeCategories
    val setAnimeDefaultEpisodeFlags: SetAnimeDefaultEpisodeFlags
    val setAnimeDefaultSeasonFlags: SetAnimeDefaultSeasonFlags
    val setAnimeDisplayMode: SetAnimeDisplayMode
    val setAnimeEpisodeFlags: SetAnimeEpisodeFlags
    val setAnimeMigrateSorting: SetAnimeMigrateSorting
    val setAnimeSeasonFlags: SetAnimeSeasonFlags
    val setAnimeViewerFlags: SetAnimeViewerFlags
    val setReadStatus: SetReadStatus
    val setSeenStatus: SetSeenStatus
    val setSortModeForAnimeCategory: SetSortModeForAnimeCategory
    val sourceManager: SourceManager
    val sourcePreferences: SourcePreferences
    val sourcesBackupCreator: SourcesBackupCreator
    val storageManager: StorageManager
    val storagePreferences: StoragePreferences
    val stremioAddonDirectory: StremioAddonDirectory
    val stremioAddonStore: StremioAddonStore
    val stremioSubtitleFinder: StremioSubtitleFinder
    val subtitleDelayMemory: SubtitleDelayMemory
    val subtitlePreferences: SubtitlePreferences
    val syncPreferences: SyncPreferences
    val toggleAnimeIncognito: ToggleAnimeIncognito
    val toggleAnimeSource: ToggleAnimeSource
    val toggleAnimeSourcePin: ToggleAnimeSourcePin
    val toggleFavoriteCustomButton: ToggleFavoriteCustomButton
    val toggleLanguage: ToggleLanguage
    val torrentInfoProvider: TorrentInfoProvider
    val torrentPreferences: TorrentPreferences
    val torrentServerApi: TorrentServerApi
    val torrentServerUtils: TorrentServerUtils
    val torznabIndexerStore: TorznabIndexerStore
    val trackEpisode: TrackEpisode
    val trackPreferences: TrackPreferences
    val trackRepository: TrackRepository
    val trackSelect: TrackSelect
    val trackerManager: TrackerManager
    val trustAnimeExtension: TrustAnimeExtension
    val uiPreferences: UiPreferences
    val unifiedLibraryPreferences: UnifiedLibraryPreferences
    val updateAnime: UpdateAnime
    val updateAnimeExtensionStores: UpdateAnimeExtensionStores
    val updateAnimeFromRemote: UpdateAnimeFromRemote
    val updateChapter: UpdateChapter
    val updateCustomButton: UpdateCustomButton
    val updateEpisode: UpdateEpisode
    val updateManga: UpdateManga
    val updateMangaFromRemote: UpdateMangaFromRemote
    val upsertAnimeHistory: UpsertAnimeHistory
    val xML: XML
}

/** The same accessors by type, for [AnimatoInjektRegistrar] to answer Injekt from. */
internal fun InjektAccessors.injektBindings(): Map<Type, () -> Any> = mapOf(
    AddAnimeExtensionStore::class.java to { addAnimeExtensionStore },
    AddAnimeTracks::class.java to { addAnimeTracks },
    AddTracks::class.java to { addTracks },
    AdvancedPlayerPreferences::class.java to { advancedPlayerPreferences },
    AnimeBackgroundCache::class.java to { animeBackgroundCache },
    AnimeCoverCache::class.java to { animeCoverCache },
    AnimeDatabaseHandler::class.java to { animeDatabaseHandler },
    AnimeDownloadCache::class.java to { animeDownloadCache },
    AnimeDownloadManager::class.java to { animeDownloadManager },
    AnimeDownloadPreferences::class.java to { animeDownloadPreferences },
    AnimeDownloadProvider::class.java to { animeDownloadProvider },
    AnimeExtensionManager::class.java to { animeExtensionManager },
    AnimeExtensionStoreRepository::class.java to { animeExtensionStoreRepository },
    AnimeFetchInterval::class.java to { animeFetchInterval },
    AnimeLibraryPreferences::class.java to { animeLibraryPreferences },
    AnimeRepository::class.java to { animeRepository },
    AnimeSourceManager::class.java to { animeSourceManager },
    AnimeSourcePreferences::class.java to { animeSourcePreferences },
    AnimeTrackPreferences::class.java to { animeTrackPreferences },
    AnimeTrackRepository::class.java to { animeTrackRepository },
    AnimeTrackerManager::class.java to { animeTrackerManager },
    Application::class.java to { application },
    AudioPreferences::class.java to { audioPreferences },
    BackupPreferences::class.java to { backupPreferences },
    BasePreferences::class.java to { basePreferences },
    CastController::class.java to { castController },
    CategoriesBackupCreator::class.java to { categoriesBackupCreator },
    CategoriesRestorer::class.java to { categoriesRestorer },
    ChapterCache::class.java to { chapterCache },
    ContentPreferences::class.java to { contentPreferences },
    Context::class.java to { context },
    CreateAnimeCategoryWithName::class.java to { createAnimeCategoryWithName },
    CreateCustomButton::class.java to { createCustomButton },
    DecoderPreferences::class.java to { decoderPreferences },
    DelayedAnimeTrackingStore::class.java to { delayedAnimeTrackingStore },
    DeleteAnimeCategory::class.java to { deleteAnimeCategory },
    DeleteAnimeTrack::class.java to { deleteAnimeTrack },
    DeleteCustomButton::class.java to { deleteCustomButton },
    DiscoverPreferences::class.java to { discoverPreferences },
    DownloadCache::class.java to { downloadCache },
    DownloadCleanupPreferences::class.java to { downloadCleanupPreferences },
    DownloadManager::class.java to { downloadManager },
    DownloadPreferences::class.java to { downloadPreferences },
    DownloadProvider::class.java to { downloadProvider },
    EntryOverrides::class.java to { entryOverrides },
    EpisodeVideoResolver::class.java to { episodeVideoResolver },
    ExtensionManager::class.java to { extensionManager },
    ExtensionStoreRestorer::class.java to { extensionStoreRestorer },
    ExtensionStoresBackupCreator::class.java to { extensionStoresBackupCreator },
    ExternalIntents::class.java to { externalIntents },
    FilterEpisodesForDownload::class.java to { filterEpisodesForDownload },
    GesturePreferences::class.java to { gesturePreferences },
    GetAnime::class.java to { getAnime },
    GetAnimeByUrlAndSourceId::class.java to { getAnimeByUrlAndSourceId },
    GetAnimeCategories::class.java to { getAnimeCategories },
    GetAnimeExtensionLanguages::class.java to { getAnimeExtensionLanguages },
    GetAnimeExtensionSources::class.java to { getAnimeExtensionSources },
    GetAnimeExtensionStoreCountAsFlow::class.java to { getAnimeExtensionStoreCountAsFlow },
    GetAnimeExtensionStores::class.java to { getAnimeExtensionStores },
    GetAnimeExtensionsByType::class.java to { getAnimeExtensionsByType },
    GetAnimeFavorites::class.java to { getAnimeFavorites },
    GetAnimeHistory::class.java to { getAnimeHistory },
    GetAnimeIncognitoState::class.java to { getAnimeIncognitoState },
    GetAnimeSeasonsByParentId::class.java to { getAnimeSeasonsByParentId },
    GetAnimeSourcesWithFavoriteCount::class.java to { getAnimeSourcesWithFavoriteCount },
    GetAnimeTracks::class.java to { getAnimeTracks },
    GetAnimeUpdates::class.java to { getAnimeUpdates },
    GetAnimeWithEpisodesAndSeasons::class.java to { getAnimeWithEpisodesAndSeasons },
    GetCategories::class.java to { getCategories },
    GetChapter::class.java to { getChapter },
    GetChaptersByMangaId::class.java to { getChaptersByMangaId },
    GetCustomButtons::class.java to { getCustomButtons },
    GetDuplicateLibraryAnime::class.java to { getDuplicateLibraryAnime },
    GetEnabledAnimeSources::class.java to { getEnabledAnimeSources },
    GetEpisode::class.java to { getEpisode },
    GetEpisodeByUrlAndAnimeId::class.java to { getEpisodeByUrlAndAnimeId },
    GetEpisodesByAnimeId::class.java to { getEpisodesByAnimeId },
    GetExtensionStoreCountAsFlow::class.java to { getExtensionStoreCountAsFlow },
    GetExtensionsByType::class.java to { getExtensionsByType },
    GetFavorites::class.java to { getFavorites },
    GetHistory::class.java to { getHistory },
    GetIncognitoState::class.java to { getIncognitoState },
    GetLanguagesWithAnimeSources::class.java to { getLanguagesWithAnimeSources },
    GetLibraryAnime::class.java to { getLibraryAnime },
    GetLibraryManga::class.java to { getLibraryManga },
    GetManga::class.java to { getManga },
    GetMangaWithChapters::class.java to { getMangaWithChapters },
    GetNextEpisodes::class.java to { getNextEpisodes },
    GetRemoteAnime::class.java to { getRemoteAnime },
    GetTracksPerAnime::class.java to { getTracksPerAnime },
    GetUnifiedLibrary::class.java to { getUnifiedLibrary },
    GetUpcomingAnime::class.java to { getUpcomingAnime },
    GetUpdates::class.java to { getUpdates },
    GetVisibleAnimeCategories::class.java to { getVisibleAnimeCategories },
    HideAnimeCategory::class.java to { hideAnimeCategory },
    ImageSaver::class.java to { imageSaver },
    InsertAnimeTrack::class.java to { insertAnimeTrack },
    JavaScriptEngine::class.java to { javaScriptEngine },
    JellyfinServerStore::class.java to { jellyfinServerStore },
    Json::class.java to { json },
    LibraryPreferences::class.java to { libraryPreferences },
    LiveChannels::class.java to { liveChannels },
    LocalAnimeBackgroundManager::class.java to { localAnimeBackgroundManager },
    LocalAnimeCoverManager::class.java to { localAnimeCoverManager },
    LocalAnimeSourceFileSystem::class.java to { localAnimeSourceFileSystem },
    LocalEpisodeThumbnailManager::class.java to { localEpisodeThumbnailManager },
    M3uPlaylistStore::class.java to { m3uPlaylistStore },
    MangaBackupCreator::class.java to { mangaBackupCreator },
    MangaRepository::class.java to { mangaRepository },
    MangaRestorer::class.java to { mangaRestorer },
    MetadataCatalog::class.java to { metadataCatalog },
    NetworkHelper::class.java to { networkHelper },
    NetworkPreferences::class.java to { networkPreferences },
    NetworkToLocalAnime::class.java to { networkToLocalAnime },
    NetworkToLocalManga::class.java to { networkToLocalManga },
    PlayerPreferences::class.java to { playerPreferences },
    PreferenceBackupCreator::class.java to { preferenceBackupCreator },
    PreferenceRestorer::class.java to { preferenceRestorer },
    PreferenceStore::class.java to { preferenceStore },
    ProtoBuf::class.java to { protoBuf },
    ProxyPreferences::class.java to { proxyPreferences },
    RefreshAnimeTracks::class.java to { refreshAnimeTracks },
    RefreshTracks::class.java to { refreshTracks },
    RememberedQuality::class.java to { rememberedQuality },
    RemoveAnimeExtensionStore::class.java to { removeAnimeExtensionStore },
    RemoveAnimeHistory::class.java to { removeAnimeHistory },
    RenameAnimeCategory::class.java to { renameAnimeCategory },
    ReorderAnimeCategory::class.java to { reorderAnimeCategory },
    ReorderCustomButton::class.java to { reorderCustomButton },
    SecurityPreferences::class.java to { securityPreferences },
    SetAnimeCategories::class.java to { setAnimeCategories },
    SetAnimeDefaultEpisodeFlags::class.java to { setAnimeDefaultEpisodeFlags },
    SetAnimeDefaultSeasonFlags::class.java to { setAnimeDefaultSeasonFlags },
    SetAnimeDisplayMode::class.java to { setAnimeDisplayMode },
    SetAnimeEpisodeFlags::class.java to { setAnimeEpisodeFlags },
    SetAnimeMigrateSorting::class.java to { setAnimeMigrateSorting },
    SetAnimeSeasonFlags::class.java to { setAnimeSeasonFlags },
    SetAnimeViewerFlags::class.java to { setAnimeViewerFlags },
    SetReadStatus::class.java to { setReadStatus },
    SetSeenStatus::class.java to { setSeenStatus },
    SetSortModeForAnimeCategory::class.java to { setSortModeForAnimeCategory },
    SourceManager::class.java to { sourceManager },
    SourcePreferences::class.java to { sourcePreferences },
    SourcesBackupCreator::class.java to { sourcesBackupCreator },
    StorageManager::class.java to { storageManager },
    StoragePreferences::class.java to { storagePreferences },
    StremioAddonDirectory::class.java to { stremioAddonDirectory },
    StremioAddonStore::class.java to { stremioAddonStore },
    StremioSubtitleFinder::class.java to { stremioSubtitleFinder },
    SubtitleDelayMemory::class.java to { subtitleDelayMemory },
    SubtitlePreferences::class.java to { subtitlePreferences },
    SyncPreferences::class.java to { syncPreferences },
    ToggleAnimeIncognito::class.java to { toggleAnimeIncognito },
    ToggleAnimeSource::class.java to { toggleAnimeSource },
    ToggleAnimeSourcePin::class.java to { toggleAnimeSourcePin },
    ToggleFavoriteCustomButton::class.java to { toggleFavoriteCustomButton },
    ToggleLanguage::class.java to { toggleLanguage },
    TorrentInfoProvider::class.java to { torrentInfoProvider },
    TorrentPreferences::class.java to { torrentPreferences },
    TorrentServerApi::class.java to { torrentServerApi },
    TorrentServerUtils::class.java to { torrentServerUtils },
    TorznabIndexerStore::class.java to { torznabIndexerStore },
    TrackEpisode::class.java to { trackEpisode },
    TrackPreferences::class.java to { trackPreferences },
    TrackRepository::class.java to { trackRepository },
    TrackSelect::class.java to { trackSelect },
    TrackerManager::class.java to { trackerManager },
    TrustAnimeExtension::class.java to { trustAnimeExtension },
    UiPreferences::class.java to { uiPreferences },
    UnifiedLibraryPreferences::class.java to { unifiedLibraryPreferences },
    UpdateAnime::class.java to { updateAnime },
    UpdateAnimeExtensionStores::class.java to { updateAnimeExtensionStores },
    UpdateAnimeFromRemote::class.java to { updateAnimeFromRemote },
    UpdateChapter::class.java to { updateChapter },
    UpdateCustomButton::class.java to { updateCustomButton },
    UpdateEpisode::class.java to { updateEpisode },
    UpdateManga::class.java to { updateManga },
    UpdateMangaFromRemote::class.java to { updateMangaFromRemote },
    UpsertAnimeHistory::class.java to { upsertAnimeHistory },
    XML::class.java to { xML },
)
